version: '2'
services:
  jmusicbot:
    build: ./musicbot
    ports:
      - 8080:8080
    env_file:
      - discord.env
  client:
    build: ./client
    ports:
      - 3000:3000
    env_file:
      - discord.env
      - nextauth.env
      - database.env
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - database.env